#!/usr/bin/ruby 
require 'getopt/std'
require 'nokogiri'
require 'open-uri'
require 'down'
doc = File.open("test.html")
homepage = Nokogiri::HTML(doc)
homepage.css('a.brick-title').each do |a|
	toLink = a["href"]
	lul = Nokogiri::HTML(open(toLink))
	dlLink = lul.at('source')[:src]
	p "Dowloading: #{dlLink}"
	Down.download(dlLink, destination: Dir.pwd + "/downloads/")
end

